apiVersion: apps/v1
kind: Deployment
metadata:
  name: clasificador-imagenes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clasificador-imagenes
  template:
    metadata:
      labels:
        app: clasificador-imagenes
    spec:
      containers:
      - name: clasificador-imagenes
        image: fcp2207/clasificador-imagenes:latest
        ports:
        - containerPort: 5000
