apiVersion: v1
kind: Service
metadata:
  name: clasificador-imagenes-service
spec:
  selector:
    app: clasificador-imagenes
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
